-- FonoAudio-Pro AI - Complete Schema Restoration (Fixed for UUID)
-- Run this in the Supabase SQL Editor to fix 404 errors and enable NBA features.

-- 1. Restore Missing Core Tables

-- Sessions Table
CREATE TABLE IF NOT EXISTS sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id uuid REFERENCES patients(id) ON DELETE CASCADE,
    date text NOT NULL,
    summary text,
    observations text,
    next_action text,
    status text DEFAULT 'completed',
    created_at timestamp with time zone DEFAULT now()
);

-- Clinical Facts Table
CREATE TABLE IF NOT EXISTS clinical_facts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id uuid REFERENCES patients(id) ON DELETE CASCADE,
    category text NOT NULL, -- 'swallowing', 'audiology', 'cognition', 'motricity', 'language', 'voice'
    fact text NOT NULL,
    evidence text,
    confidence numeric DEFAULT 1.0,
    created_at timestamp with time zone DEFAULT now()
);

-- Candidate Resources Table
CREATE TABLE IF NOT EXISTS candidate_resources (
    id text PRIMARY KEY,
    title text NOT NULL,
    description text,
    url text,
    source text,
    category text,
    tags text[] DEFAULT '{}',
    status text DEFAULT 'pending', -- 'pending', 'approved', 'rejected'
    created_at timestamp with time zone DEFAULT now()
);

-- 2. Implement NBA (Next Best Action) Architecture

-- NBA Suggestions Table
CREATE TABLE IF NOT EXISTS nba_suggestions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    module_id text NOT NULL,
    action_id text NOT NULL UNIQUE,
    title text NOT NULL,
    description text NOT NULL,
    rationale text,
    triggering_facts jsonb,
    knowledge_artifacts_used text[],
    confidence_or_strength numeric,
    status text NOT NULL DEFAULT 'pending', -- 'pending', 'accepted', 'rejected', 'edited'
    session_id uuid
);

-- NBA Decisions Table
CREATE TABLE IF NOT EXISTS nba_decisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    patient_id uuid NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    suggestion_id bigint REFERENCES nba_suggestions(id),
    action_id text NOT NULL,
    original_action_id text,
    action_type text NOT NULL,
    category text,
    rationale text,
    triggering_facts jsonb,
    knowledge_artifacts_used text[],
    confidence_or_strength numeric,
    clinician_disposition text NOT NULL, -- 'accepted', 'rejected', 'edited'
    disposition_reason text,
    metadata jsonb,
    session_id uuid
);

-- 3. Row Level Security (RLS)

ALTER TABLE sessions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for all users" ON sessions FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE clinical_facts ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for all users" ON clinical_facts FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE candidate_resources ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for all users" ON candidate_resources FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE nba_suggestions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for all users" ON nba_suggestions FOR ALL USING (true) WITH CHECK (true);

ALTER TABLE nba_decisions ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Enable all access for all users" ON nba_decisions FOR ALL USING (true) WITH CHECK (true);

-- 4. Indexes for Performance
CREATE INDEX IF NOT EXISTS idx_sessions_patient ON sessions(patient_id);
CREATE INDEX IF NOT EXISTS idx_clinical_facts_patient_category ON clinical_facts(patient_id, category);
CREATE INDEX IF NOT EXISTS idx_nba_suggestions_patient ON nba_suggestions(patient_id);
CREATE INDEX IF NOT EXISTS idx_nba_decisions_patient ON nba_decisions(patient_id);

