-- FonoAudio-Pro AI - MASTER SCHEMA RESTORATION
-- This script restores ALL required tables for the app to function without 404s.

-- 1. PATIENTS (The Root)
CREATE TABLE IF NOT EXISTS patients (
    id text PRIMARY KEY,
    name text NOT NULL,
    age numeric,
    diagnosis text,
    document text,
    phone text,
    email text,
    notes text,
    history jsonb DEFAULT '[]'::jsonb,
    evaluations jsonb DEFAULT '[]'::jsonb,
    documents jsonb DEFAULT '[]'::jsonb,
    reports jsonb DEFAULT '[]'::jsonb,
    "treatmentPlan" jsonb DEFAULT '{}'::jsonb,
    anamnesis jsonb DEFAULT '{}'::jsonb,
    location text,
    responsable text,
    derivante text,
    obraSocial text,
    consentSigned boolean DEFAULT false,
    alerts text[] DEFAULT '{}'
);

-- 2. APPOINTMENTS
CREATE TABLE IF NOT EXISTS appointments (
    id text PRIMARY KEY,
    patient_id text REFERENCES patients(id) ON DELETE CASCADE,
    patient_name text,
    type text,
    status text CHECK (status IN ('pending', 'completed', 'cancelled')),
    date text,
    time text,
    meetLink text
);

-- 3. SESSIONS (Core for Clinical History)
CREATE TABLE IF NOT EXISTS sessions (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id text REFERENCES patients(id) ON DELETE CASCADE,
    date text NOT NULL,
    summary text,
    observations text,
    next_action text,
    status text DEFAULT 'completed',
    created_at timestamp with time zone DEFAULT now()
);

-- 4. CLINICAL FACTS (For the Analysis Panels)
CREATE TABLE IF NOT EXISTS clinical_facts (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id text REFERENCES patients(id) ON DELETE CASCADE,
    category text NOT NULL, -- 'swallowing', 'audiology', 'cognition', 'motricity', 'language', 'voice'
    fact text NOT NULL,
    evidence text,
    confidence numeric DEFAULT 1.0,
    created_at timestamp with time zone DEFAULT now()
);

-- 5. ANALYSIS HISTORY (For Longitudinal Tracking)
CREATE TABLE IF NOT EXISTS analysis_history (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id text REFERENCES patients(id) ON DELETE CASCADE,
    module_id text NOT NULL,
    analysis_data jsonb NOT NULL,
    result_summary text,
    created_at timestamp with time zone DEFAULT now()
);

-- 6. HOME GUIDES (The output for families)
CREATE TABLE IF NOT EXISTS home_guides (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id text REFERENCES patients(id) ON DELETE CASCADE,
    title text NOT NULL,
    content jsonb NOT NULL,
    version int DEFAULT 1,
    status text DEFAULT 'draft', -- 'draft', 'final', 'sent'
    delivery_method text,
    sent_at timestamp with time zone,
    share_token text,
    updated_at timestamp with time zone DEFAULT now(),
    created_at timestamp with time zone DEFAULT now()
);

-- 7. MATERIALS LIBRARY
CREATE TABLE IF NOT EXISTS materials (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    title text NOT NULL,
    category text,
    type text,
    format text,
    url text,
    verified boolean DEFAULT false,
    clinical_area text,
    tags text[] DEFAULT '{}',
    created_at timestamp with time zone DEFAULT now()
);

-- 8. CANDIDATE RESOURCES (The Review Tray)
CREATE TABLE IF NOT EXISTS candidate_resources (
    id text PRIMARY KEY,
    title text NOT NULL,
    description text,
    url text,
    source text,
    category text,
    tags text[] DEFAULT '{}',
    status text DEFAULT 'pending',
    created_at timestamp with time zone DEFAULT now()
);

-- 9. NBA SUGGESTIONS (AI-generated "Next Best Actions")
CREATE TABLE IF NOT EXISTS nba_suggestions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    patient_id text NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    module_id text NOT NULL,
    action_id text NOT NULL UNIQUE,
    title text NOT NULL,
    description text NOT NULL,
    rationale text,
    triggering_facts jsonb,
    knowledge_artifacts_used text[],
    confidence_or_strength numeric,
    status text NOT NULL DEFAULT 'pending',
    session_id uuid
);

-- 10. NBA DECISIONS (Clinician's response to AI)
CREATE TABLE IF NOT EXISTS nba_decisions (
    id bigint GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    created_at timestamp with time zone DEFAULT timezone('utc'::text, now()) NOT NULL,
    patient_id text NOT NULL REFERENCES patients(id) ON DELETE CASCADE,
    suggestion_id bigint REFERENCES nba_suggestions(id),
    action_id text NOT NULL,
    original_action_id text,
    action_type text NOT NULL,
    category text,
    rationale text,
    triggering_facts jsonb,
    knowledge_artifacts_used text[],
    confidence_or_strength numeric,
    clinician_disposition text NOT NULL, -- 'accepted', 'rejected', 'edited'
    disposition_reason text,
    metadata jsonb,
    session_id uuid
);

-- 11. RAG Embeddings
CREATE EXTENSION IF NOT EXISTS vector;
CREATE TABLE IF NOT EXISTS clinical_embeddings (
    id uuid PRIMARY KEY DEFAULT gen_random_uuid(),
    patient_id text REFERENCES patients(id) ON DELETE CASCADE,
    content text NOT NULL,
    embedding vector(1536),
    metadata jsonb DEFAULT '{}'::jsonb,
    created_at timestamp with time zone DEFAULT now()
);

-- 12. RLS Policies (Public for demo)
DO $$ 
DECLARE 
    tbl text;
    tables text[] := ARRAY['patients', 'appointments', 'sessions', 'clinical_facts', 'analysis_history', 'home_guides', 'materials', 'candidate_resources', 'nba_suggestions', 'nba_decisions', 'clinical_embeddings'];
BEGIN 
    FOREACH tbl IN ARRAY tables LOOP
        EXECUTE format('ALTER TABLE %I ENABLE ROW LEVEL SECURITY;', tbl);
        EXECUTE format('CREATE POLICY "Enable all access" ON %I FOR ALL USING (true) WITH CHECK (true);', tbl);
    END LOOP;
END $$;

-- Indexes
CREATE INDEX IF NOT EXISTS idx_patients_name ON patients(name);
CREATE INDEX IF NOT EXISTS idx_sessions_patient ON sessions(patient_id);
CREATE INDEX IF NOT EXISTS idx_facts_patient_cat ON clinical_facts(patient_id, category);
CREATE INDEX IF NOT EXISTS idx_guides_patient ON home_guides(patient_id);
CREATE INDEX IF NOT EXISTS idx_nba_sug_patient ON nba_suggestions(patient_id);
CREATE INDEX IF NOT EXISTS idx_nba_dec_patient ON nba_decisions(patient_id);
