-- Create table for assistant knowledge base
create table if not exists assistant_knowledge (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  title text not null,
  content text not null,
  tags text[] default '{}'::text[]
);

-- Enable Row Level Security (RLS)
alter table assistant_knowledge enable row level security;

-- Create policy to allow all operations for authenticated users (or anon for this demo)
create policy "Enable all access for all users" on assistant_knowledge
  for all using (true) with check (true);

-- Create text search index for better querying
create index if not exists assistant_knowledge_content_idx on assistant_knowledge using gin(to_tsvector('spanish', content));

-- Create table for clinical notes (shared with fononote-ai)
create table if not exists notas_clinicas (
  id bigint generated by default as identity primary key,
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  patient_name text not null,
  transcription text,
  dialogue_json jsonb,
  summary text,
  category text,
  tags text[],
  audio_url text,
  duration numeric
);

-- Enable RLS for notas_clinicas
alter table notas_clinicas enable row level security;

-- Create policy to allow all operations for authenticated users (or anon for this demo)
create policy "Enable all access for all users" on notas_clinicas
  for all using (true) with check (true);
