-- FonoAudio-Pro AI - Complete Database Setup
-- Execute this in your Supabase SQL Editor to set up all required tables

-- 1. Core Clinical Tables
create table if not exists patients (
    id text primary key,
    name text not null,
    age numeric,
    diagnosis text,
    document text,
    phone text,
    email text,
    notes text,
    history jsonb default '[]'::jsonb,
    evaluations jsonb default '[]'::jsonb,
    documents jsonb default '[]'::jsonb,
    reports jsonb default '[]'::jsonb,
    "treatmentPlan" jsonb default '{}'::jsonb,
    anamnesis jsonb default '{}'::jsonb,
    location text,
    responsable text,
    derivante text,
    obraSocial text,
    consentSigned boolean default false,
    alerts text[] default '{}'
);

create table if not exists appointments (
    id text primary key,
    "patientId" text references patients(id),
    "patientName" text,
    patient_id text,
    patient_name text,
    type text,
    status text check (status in ('pending', 'completed', 'cancelled')),
    date text,
    time text,
    meetLink text
);

create table if not exists notas_clinicas (
    id bigint generated by default as identity primary key,
    created_at timestamp with time zone default timezone('utc'::text, now()) not null,
    patient_name text not null,
    transcription text,
    dialogue_json jsonb,
    summary text,
    category text,
    tags text[],
    audio_url text,
    duration numeric
);

-- 2. Materials Library Table
create table if not exists materials (
    id uuid primary key default gen_random_uuid(),
    title text not null,
    category text,
    type text, -- propios, externos, redes
    format text,
    url text,
    verified boolean default false,
    created_at timestamp with time zone default now()
);

-- 3. RAG System Tables (NotebookLM Replacement)
-- Enable the vector extension (required for embeddings)
create extension if not exists vector;

create table if not exists clinical_embeddings (
    id uuid primary key default gen_random_uuid(),
    patient_id uuid references patients(id) on delete set null,
    content text not null,
    embedding vector(1536), -- Gemini text-embedding-001 produces 1536-dim vectors
    metadata jsonb default '{}'::jsonb,
    created_at timestamp with time zone default now()
);

-- Index for fast similarity search
create index if not exists clinical_embeddings_embedding_idx on clinical_embeddings using ivfflat (embedding vector_cosine_ops) with (lists = 100);

-- 4. Row Level Security (RLS) Policies
-- Enable RLS on all tables
alter table patients enable row level security;
alter table appointments enable row level security;
alter table notas_clinicas enable row level security;
alter table materials enable row level security;
alter table clinical_embeddings enable row level security;

-- Policies for public access (appropriate for this demo app)
-- In a production environment, you would use proper authentication
create policy "Enable all access for all users" on patients
    for all using (true) with check (true);

create policy "Enable all access for all users" on appointments
    for all using (true) with check (true);

create policy "Enable all access for all users" on notas_clinicas
    for all using (true) with check (true);

create policy "Enable all access for all users" on materials
    for all using (true) with check (true);

create policy "Enable all access for all users" on clinical_embeddings
    for all using (true) with check (true);

-- 5. Useful Indexes for Performance
create index if not exists idx_patients_name on patients(name);
create index if not exists idx_appointments_date on appointments(date);
create index if not exists idx_materials_title on materials(title);
create index if not exists idx_materials_category on materials(category);

-- 6. Insert Default Materials (Optional)
-- Uncomment and modify if you want to pre-populate the materials library
/*
insert into materials (title, category, type, format, url, verified) values
('Tablero Lúdico Fonema /rr/', 'Habla', 'propios', 'PDF / Lámina', '#', true),
('Guía Miofuncional para Familias - Deglución', 'Disfagia', 'propios', 'Documento', '#', true),
('Ejercicios de Coordinación Fono-Respiratoria', 'Voz', 'propios', 'Guía', '#', true),
('Paper: Evidencia Científica en Terapia TEL Reciente', 'Investigación', 'externos', 'Académico', '#', true),
('Protocolo Clínico de Valoración Vocal G.R.B.A.S.', 'Voz', 'externos', 'Protocolo', '#', true)
on conflict do nothing;
*/

-- 7. Validation Comments
-- Patients table: Stores all patient information including treatment plans and history
-- Appointments table: Tracks scheduled appointments with status and meet links
-- Notas clínicas: Stores voice transcriptions and clinical notes from audio recordings
-- Materials table: Library of clinical resources that can be shared with patients
-- Clinical_embeddings: Vector database for semantic search (replaces NotebookLM functionality)
-- RLS Policies: Allow full access for this demo (secure properly for production)

-- To verify installation, run:
-- SELECT count(*) FROM patients;
-- SELECT count(*) FROM appointments;
-- SELECT count(*) FROM notas_clinicas;
-- SELECT count(*) FROM materials;
-- SELECT count(*) FROM clinical_embeddings;